name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.8.20417.9

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore --version-suffix ${{ github.run_number }}

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish NuGet
      run: dotnet nuget push "**/*.nupkg" -s "${{ secrets.NUGET_SOURCE }}" -k "${{ secrets.NUGET_PUBLISH_API_KEY }}" --skip-duplicate
