name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.8.20417.9

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore --version-suffix ${{ github.run_number }}

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        path: "**/*.nupkg"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.5
    
    - name: Publish NuGet
      run: dotnet nuget push "**/*.nupkg" -s "${{ secrets.NUGET_SOURCE }}" -k "${{ secrets.NUGET_PUBLISH_API_KEY }}" --skip-duplicate

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
